In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,
                         columns=['國文', '英文', '數學', '地理', '歷史'],
                         index=range(1,51)
                         )
scores_pd

    國文   英文   數學   地理   歷史
1   56   85   82   83   68
2   75   91   74   51   80
3   65   59   85   76   59
4   76   76   70   89   70
5   98   89   65   68   74
6   98   53   82   94   82
7   73   95   52   59   56
8   81   68   90  100   80
9   54   52   64   77   97
10  65   74   56   74   80
11  88   89   51   99   85
12  94   78   87   81   62
13  59   61   60   61   95
14  82   94   79   64   71
15  81   79   60   52   92
16  74   95   74   76   91
17  79   80   69   95   88
18  51   84   89   58  100
19  84   75   98   54   89
20  83   79   53   75   82
21  77   53   59   71   83
22  79   65   76   91   91
23  72   61   61   86   78
24  68   59   89   86   67
25  53   51   88   77   60
26  90   77   66   79   51
27  78   78   89   56   69
28  93   74   73   97   77
29  59   64   72   96   71
30  81   75   77   90   75
31  96   63   77   80   64
32  60   94  100   50   66
33  89   80   82   60   89
34  85   52   51   79   54
35  60   72   58   70   66
36  84   77   89   58   60
37  85   67   62   93   70
38  58  100   70   72   83
39  96   97   62   84   53
40  70   83   54   58   63
41  94   95   84   73   68
42  91   97   95   88   94
43  97   58   65   87   64
44  73   65   77   92   63
45  83   61   52   86   76
46  79   97   57   61   73
47  93   79   56   77   62
48  62   72   91   89   86
49  62   87   52   77   81
50  80   79   64   53   98

In [5]:
def callback1(value:pd.Series):
    return pd.Series([value.max(), value.min(), value.median(), value.mean()],
                     index=['最高分', '最低分', '中間值', '平均值'])

scores_pd.apply(callback1)

        國文      英文      數學      地理      歷史
最高分  98.00  100.00  100.00  100.00  100.00
最低分  51.00   51.00   51.00   50.00   51.00
中間值  79.00   77.00   71.00   77.00   74.50
平均值  77.26   75.76   71.76   76.04   75.12