In [1]:
#建立並整理隨機亂數的2維資料
import numpy as np
import pandas as pd
scores = np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,
                         columns=['國文', '英文', '數學', '地理', '歷史'],
                         index=range(1,51)
                         )
scores_pd

    國文  英文   數學  地理  歷史
1   58  86   60  82  78
2   60  83   74  76  68
3   88  60  100  78  54
4   53  77   74  53  67
5   55  73   52  79  91
6   59  84   82  86  99
7   87  75   58  68  66
8   59  51   87  83  56
9   84  81   75  50  72
10  87  53   62  99  73
11  56  87   82  69  78
12  55  98   96  91  88
13  79  78   64  87  75
14  96  93   55  76  72
15  55  61   86  78  81
16  70  94  100  59  79
17  57  91   85  70  71
18  96  75   98  72  99
19  59  58   66  84  77
20  69  53   58  76  89
21  84  79   73  79  99
22  68  96   87  70  99
23  55  68   68  65  78
24  52  80   64  67  81
25  61  86   82  53  61
26  92  95   59  99  59
27  86  59   70  55  57
28  70  87   51  50  63
29  77  89   53  94  79
30  79  56   68  86  86
31  67  57   86  77  93
32  80  79   59  67  51
33  60  61   57  66  93
34  63  84   89  92  78
35  67  99   93  85  81
36  62  85   63  81  71
37  96  81   54  73  83
38  71  94  100  75  95
39  70  67   92  69  54
40  54  83   61  95  56
41  81  66   82  61  56
42  70  56   79  82  86
43  68  52   86  67  53
44  54  66   94  82  64
45  89  74   99  82  72
46  57  56   79  81  94
47  74  74   56  85  67
48  51  52   52  79  77
49  91  63   80  78  87
50  78  76   92  76  51

In [2]:
scores_pd.index.name='學號'
scores_pd.columns.name='科目'
scores_pd

科目  國文  英文   數學  地理  歷史
學號
1   58  86   60  82  78
2   60  83   74  76  68
3   88  60  100  78  54
4   53  77   74  53  67
5   55  73   52  79  91
6   59  84   82  86  99
7   87  75   58  68  66
8   59  51   87  83  56
9   84  81   75  50  72
10  87  53   62  99  73
11  56  87   82  69  78
12  55  98   96  91  88
13  79  78   64  87  75
14  96  93   55  76  72
15  55  61   86  78  81
16  70  94  100  59  79
17  57  91   85  70  71
18  96  75   98  72  99
19  59  58   66  84  77
20  69  53   58  76  89
21  84  79   73  79  99
22  68  96   87  70  99
23  55  68   68  65  78
24  52  80   64  67  81
25  61  86   82  53  61
26  92  95   59  99  59
27  86  59   70  55  57
28  70  87   51  50  63
29  77  89   53  94  79
30  79  56   68  86  86
31  67  57   86  77  93
32  80  79   59  67  51
33  60  61   57  66  93
34  63  84   89  92  78
35  67  99   93  85  81
36  62  85   63  81  71
37  96  81   54  73  83
38  71  94  100  75  95
39  70  67   92  69  54
40  54  83   61  95  56
41  81  66   82  61  56
42  70  56   79  82  86
43  68  52   86  67  53
44  54  66   94  82  64
45  89  74   99  82  72
46  57  56   79  81  94
47  74  74   56  85  67
48  51  52   52  79  77
49  91  63   80  78  87
50  78  76   92  76  51

In [3]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]

學號
1     58
2     60
3     88
4     53
5     55
6     59
7     87
8     59
9     84
10    87
Name: 國文, dtype: int64

學號
1      60
2      74
3     100
4      74
5      52
6      82
7      58
8      87
9      75
10     62
Name: 數學, dtype: int64

In [4]:
#只要有相同的索引，就可以直接做數學的運算
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     118
2     134
3     188
4     127
5     107
6     141
7     145
8     146
9     159
10    149
dtype: int64

In [5]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['數學'] + scores_pd['地理'] + scores_pd['歷史']

學號
1     364
2     361
3     380
4     324
5     350
6     410
7     354
8     336
9     362
10    374
11    372
12    428
13    383
14    392
15    361
16    402
17    374
18    440
19    344
20    345
21    414
22    420
23    334
24    344
25    343
26    404
27    327
28    321
29    392
30    375
31    380
32    336
33    337
34    406
35    425
36    362
37    387
38    435
39    352
40    349
41    346
42    373
43    326
44    360
45    416
46    367
47    356
48    311
49    399
50    373
dtype: int64

In [6]:
#統計的實體方法，sum()和mean()
scores_pd['總分'] = scores_pd[['國文', '英文', '數學', '地理', '歷史']].sum(axis=1)
scores_pd['平均'] = scores_pd[['國文', '英文', '數學', '地理', '歷史']].mean(axis=1)
scores_pd

科目  國文  英文   數學  地理  歷史   總分    平均
學號
1   58  86   60  82  78  364  72.8
2   60  83   74  76  68  361  72.2
3   88  60  100  78  54  380  76.0
4   53  77   74  53  67  324  64.8
5   55  73   52  79  91  350  70.0
6   59  84   82  86  99  410  82.0
7   87  75   58  68  66  354  70.8
8   59  51   87  83  56  336  67.2
9   84  81   75  50  72  362  72.4
10  87  53   62  99  73  374  74.8
11  56  87   82  69  78  372  74.4
12  55  98   96  91  88  428  85.6
13  79  78   64  87  75  383  76.6
14  96  93   55  76  72  392  78.4
15  55  61   86  78  81  361  72.2
16  70  94  100  59  79  402  80.4
17  57  91   85  70  71  374  74.8
18  96  75   98  72  99  440  88.0
19  59  58   66  84  77  344  68.8
20  69  53   58  76  89  345  69.0
21  84  79   73  79  99  414  82.8
22  68  96   87  70  99  420  84.0
23  55  68   68  65  78  334  66.8
24  52  80   64  67  81  344  68.8
25  61  86   82  53  61  343  68.6
26  92  95   59  99  59  404  80.8
27  86  59   70  55  57  327  65.4
28  70  87   51  50  63  321  64.2
29  77  89   53  94  79  392  78.4
30  79  56   68  86  86  375  75.0
31  67  57   86  77  93  380  76.0
32  80  79   59  67  51  336  67.2
33  60  61   57  66  93  337  67.4
34  63  84   89  92  78  406  81.2
35  67  99   93  85  81  425  85.0
36  62  85   63  81  71  362  72.4
37  96  81   54  73  83  387  77.4
38  71  94  100  75  95  435  87.0
39  70  67   92  69  54  352  70.4
40  54  83   61  95  56  349  69.8
41  81  66   82  61  56  346  69.2
42  70  56   79  82  86  373  74.6
43  68  52   86  67  53  326  65.2
44  54  66   94  82  64  360  72.0
45  89  74   99  82  72  416  83.2
46  57  56   79  81  94  367  73.4
47  74  74   56  85  67  356  71.2
48  51  52   52  79  77  311  62.2
49  91  63   80  78  87  399  79.8
50  78  76   92  76  51  373  74.6

In [7]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min', ascending=False)
scores_pd

科目  國文  英文   數學  地理  歷史   總分    平均    排名
學號
1   58  86   60  82  78  364  72.8  26.0
2   60  83   74  76  68  361  72.2  29.0
3   88  60  100  78  54  380  76.0  17.0
4   53  77   74  53  67  324  64.8  48.0
5   55  73   52  79  91  350  70.0  35.0
6   59  84   82  86  99  410  82.0   8.0
7   87  75   58  68  66  354  70.8  33.0
8   59  51   87  83  56  336  67.2  43.0
9   84  81   75  50  72  362  72.4  27.0
10  87  53   62  99  73  374  74.8  20.0
11  56  87   82  69  78  372  74.4  24.0
12  55  98   96  91  88  428  85.6   3.0
13  79  78   64  87  75  383  76.6  16.0
14  96  93   55  76  72  392  78.4  13.0
15  55  61   86  78  81  361  72.2  29.0
16  70  94  100  59  79  402  80.4  11.0
17  57  91   85  70  71  374  74.8  20.0
18  96  75   98  72  99  440  88.0   1.0
19  59  58   66  84  77  344  68.8  39.0
20  69  53   58  76  89  345  69.0  38.0
21  84  79   73  79  99  414  82.8   7.0
22  68  96   87  70  99  420  84.0   5.0
23  55  68   68  65  78  334  66.8  45.0
24  52  80   64  67  81  344  68.8  39.0
25  61  86   82  53  61  343  68.6  41.0
26  92  95   59  99  59  404  80.8  10.0
27  86  59   70  55  57  327  65.4  46.0
28  70  87   51  50  63  321  64.2  49.0
29  77  89   53  94  79  392  78.4  13.0
30  79  56   68  86  86  375  75.0  19.0
31  67  57   86  77  93  380  76.0  17.0
32  80  79   59  67  51  336  67.2  43.0
33  60  61   57  66  93  337  67.4  42.0
34  63  84   89  92  78  406  81.2   9.0
35  67  99   93  85  81  425  85.0   4.0
36  62  85   63  81  71  362  72.4  27.0
37  96  81   54  73  83  387  77.4  15.0
38  71  94  100  75  95  435  87.0   2.0
39  70  67   92  69  54  352  70.4  34.0
40  54  83   61  95  56  349  69.8  36.0
41  81  66   82  61  56  346  69.2  37.0
42  70  56   79  82  86  373  74.6  22.0
43  68  52   86  67  53  326  65.2  47.0
44  54  66   94  82  64  360  72.0  31.0
45  89  74   99  82  72  416  83.2   6.0
46  57  56   79  81  94  367  73.4  25.0
47  74  74   56  85  67  356  71.2  32.0
48  51  52   52  79  77  311  62.2  50.0
49  91  63   80  78  87  399  79.8  12.0
50  78  76   92  76  51  373  74.6  22.0

In [8]:
scores_pd.sort_values(by='排名')

科目  國文  英文   數學  地理  歷史   總分    平均    排名
學號
18  96  75   98  72  99  440  88.0   1.0
38  71  94  100  75  95  435  87.0   2.0
12  55  98   96  91  88  428  85.6   3.0
35  67  99   93  85  81  425  85.0   4.0
22  68  96   87  70  99  420  84.0   5.0
45  89  74   99  82  72  416  83.2   6.0
21  84  79   73  79  99  414  82.8   7.0
6   59  84   82  86  99  410  82.0   8.0
34  63  84   89  92  78  406  81.2   9.0
26  92  95   59  99  59  404  80.8  10.0
16  70  94  100  59  79  402  80.4  11.0
49  91  63   80  78  87  399  79.8  12.0
29  77  89   53  94  79  392  78.4  13.0
14  96  93   55  76  72  392  78.4  13.0
37  96  81   54  73  83  387  77.4  15.0
13  79  78   64  87  75  383  76.6  16.0
31  67  57   86  77  93  380  76.0  17.0
3   88  60  100  78  54  380  76.0  17.0
30  79  56   68  86  86  375  75.0  19.0
17  57  91   85  70  71  374  74.8  20.0
10  87  53   62  99  73  374  74.8  20.0
42  70  56   79  82  86  373  74.6  22.0
50  78  76   92  76  51  373  74.6  22.0
11  56  87   82  69  78  372  74.4  24.0
46  57  56   79  81  94  367  73.4  25.0
1   58  86   60  82  78  364  72.8  26.0
9   84  81   75  50  72  362  72.4  27.0
36  62  85   63  81  71  362  72.4  27.0
2   60  83   74  76  68  361  72.2  29.0
15  55  61   86  78  81  361  72.2  29.0
44  54  66   94  82  64  360  72.0  31.0
47  74  74   56  85  67  356  71.2  32.0
7   87  75   58  68  66  354  70.8  33.0
39  70  67   92  69  54  352  70.4  34.0
5   55  73   52  79  91  350  70.0  35.0
40  54  83   61  95  56  349  69.8  36.0
41  81  66   82  61  56  346  69.2  37.0
20  69  53   58  76  89  345  69.0  38.0
19  59  58   66  84  77  344  68.8  39.0
24  52  80   64  67  81  344  68.8  39.0
25  61  86   82  53  61  343  68.6  41.0
33  60  61   57  66  93  337  67.4  42.0
32  80  79   59  67  51  336  67.2  43.0
8   59  51   87  83  56  336  67.2  43.0
23  55  68   68  65  78  334  66.8  45.0
27  86  59   70  55  57  327  65.4  46.0
43  68  52   86  67  53  326  65.2  47.0
4   53  77   74  53  67  324  64.8  48.0
28  70  87   51  50  63  321  64.2  49.0
48  51  52   52  79  77  311  62.2  50.0

In [9]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'
    
scores_pd[['國文', '英文', '數學', '地理', '歷史']].style.format(format60)

In [16]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文', '英文', '數學', '地理', '歷史'],
                   props='color:black;background-color:red')\
.format(precision=0, subset=['平均','排名'])\
.to_excel('scores.xlsx')